### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [VladislavKiel/prj-rev-bwfs-dasmoto#6]
https://github.com/VladislavKiel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L17-L39

There is a lot of repetition occurring in these rules and there are opportunities for refactoring. Try to extract the common styles into a single rule with a more general selector.

You've also missed the font-family style on several elements entirely. Consider using `*` to apply that style to all elements by default.

Example:

```css
* {
  font-family: Helvetica;
}

.product h2 {
  color: white;
  font-weight: bold;
  font-size: 32px;
}

#frames {
  background-color: lightcoral;
}
```
